// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// Registers documented components and elements used in their examples so
// the component browser can render live previews.
import '@jack-henry/jh-elements/components/button/button.js'
import '@jack-henry/jh-icons/icons-wc/icon-arrow-down-to-line.js'
