// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-badge>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "count",
      "type": "string",
      "description": "Number to show within the badge. If no `count` is supplied, Badge will render as a dot.",
      "tier": "common"
    },
    {
      "name": "max-count",
      "type": "number",
      "default": "99",
      "description": "Sets the max count to show. Appends `+` to the `max-count` when value is exceeded.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": []
}
