// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-button>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "appearance",
      "type": "'primary'|'secondary'|'tertiary'|'danger'",
      "default": "secondary",
      "description": "Determines the button color.",
      "tier": "common"
    },
    {
      "name": "block",
      "type": "boolean",
      "default": "false",
      "description": "Sets the button width to its parent container.",
      "tier": "common"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "default": "false",
      "description": "Disables the button and prevents all user interactions. May cause button to be ignored by assistive technologies(AT). See `accessible-disabled` attribute if the button should remain perceivable to AT.",
      "tier": "common"
    },
    {
      "name": "href",
      "type": "string",
      "description": "Sets the link's destination.",
      "tier": "common"
    },
    {
      "name": "pending",
      "type": "boolean",
      "default": "false",
      "description": "Displays a progress indicator.",
      "tier": "common"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Describes the intent of the button.",
      "tier": "common"
    },
    {
      "name": "size",
      "type": "'x-small'|'small'|'medium'|'large'",
      "default": "medium",
      "description": "Sets the size of the button.",
      "tier": "common"
    },
    {
      "name": "submit",
      "type": "boolean",
      "default": "false",
      "description": "Sets button `type='submit'`. Button defaults to `type='button'`.",
      "tier": "common"
    },
    {
      "name": "target",
      "type": "'_blank'|'_self'|'_parent'|'_top'",
      "description": "Specifies where to display the linked URL set by the `href` property.",
      "tier": "common"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Sets the value of the button.",
      "tier": "common"
    },
    {
      "name": "accessible-disabled",
      "type": "'true'|'false'",
      "description": "Sets an `aria-disabled` to signify to screen readers that the disabled button should remain perceivable while disabled.",
      "tier": "advanced"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Sets the name of the button data when submitted in a form.",
      "tier": "advanced"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "jh-button-icon-left",
      "description": "Use to insert an icon on the left side of the button and for single icon buttons."
    },
    {
      "name": "jh-button-icon-right",
      "description": "Use to insert an icon on the right side of the button and for single icon buttons."
    }
  ]
}
