// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-card>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "footer-divider-inset",
      "type": "0|8|16|24|32|40|48|56|64|72|80|88|96",
      "description": "Sets the alignment of the left edge of the divider above the footer.",
      "tier": "common"
    },
    {
      "name": "header-divider-inset",
      "type": "0|8|16|24|32|40|48|56|64|72|80|88|96",
      "description": "Sets the alignment of the left edge of the divider below the header.",
      "tier": "common"
    },
    {
      "name": "title-heading-level",
      "type": "1|2|3|4|5|6",
      "default": "2",
      "description": "Informs assistive technologies what heading level the card title represents. Defaults to h2.",
      "tier": "common"
    },
    {
      "name": "padding",
      "type": "'small'|'medium'|'none'",
      "default": "medium",
      "description": "Sets padding on all slots. Set `padding='none'` to remove padding solely from default slot. To override padding property, set component level token for desired slot.",
      "tier": "common"
    },
    {
      "name": "show-footer-divider",
      "type": "boolean",
      "default": "false",
      "description": "Adds a divider above the footer to create a clearer definition between the body and footer.",
      "tier": "common"
    },
    {
      "name": "show-header-divider",
      "type": "boolean",
      "default": "false",
      "description": "Adds a divider below the header to create a clearer definition between the header and body.",
      "tier": "common"
    },
    {
      "name": "header-subtitle",
      "type": "string",
      "description": "Adds additional information about the card below the title.",
      "tier": "common"
    },
    {
      "name": "header-title",
      "type": "string",
      "description": "Provides context for the content of the card.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert card body content."
    },
    {
      "name": "jh-card-media",
      "description": "Use to insert media content in the top section of the card. User may need to add addtional styling to elements such as border, object-fit, etc."
    },
    {
      "name": "jh-card-header",
      "description": "Use to insert custom card header layout. Default layout includes `headerTitle` and `headerSubtitle` properties."
    },
    {
      "name": "jh-card-footer",
      "description": "Use to insert card footer content."
    }
  ]
}
