// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-divider>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "inset",
      "type": "0|8|16|24|32|40|48|56|64|72|80|88|96",
      "description": "The alignment of the left edge of the divider.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": []
}
