// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-icon>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "size",
      "type": "'x-small'|'small'|'medium'|'large'|'x-large'",
      "default": "medium",
      "description": "Sets the size of the icon.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert the icon SVG content."
    }
  ]
}
