// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-input-url>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "disabled",
      "type": "boolean",
      "default": "false",
      "description": "Disables the input and prevents all user interactions. May cause the input to be ignored by assistive technologies (AT).",
      "tier": "common"
    },
    {
      "name": "error-text",
      "type": "string",
      "description": "Text to be displayed when input has failed validation and `invalid` is true.",
      "tier": "common"
    },
    {
      "name": "helper-text",
      "type": "string",
      "description": "Provides additional context or guidance for using the input. For `helper-text` to be displayed, the `label` property must also be set.",
      "tier": "common"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "default": "false",
      "description": "Sets an `aria-invalid` attribute on input to indicate the value supplied was invalid. Also displays `error-text` and error state styling when set.",
      "tier": "common"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Identifies what data should be entered into the input field.",
      "tier": "common"
    },
    {
      "name": "maxlength",
      "type": "string",
      "description": "Sets the maximum number of characters a user can enter into the field.",
      "tier": "common"
    },
    {
      "name": "minlength",
      "type": "string",
      "description": "Sets the minimum number of characters a user can enter into the field.",
      "tier": "common"
    },
    {
      "name": "readonly",
      "type": "boolean",
      "default": "false",
      "description": "Prevents users from changing the input value. Removes all slotted content.",
      "tier": "common"
    },
    {
      "name": "required",
      "type": "boolean",
      "default": "false",
      "description": "Indicates a value is required.",
      "tier": "common"
    },
    {
      "name": "show-char-count",
      "type": "boolean",
      "default": "false",
      "description": "Displays a character counter at the bottom right corner below the input field.",
      "tier": "common"
    },
    {
      "name": "show-clear-button",
      "type": "boolean",
      "default": "false",
      "description": "Displays a clear button in the input field when it contains a value and is focused or hovered. Deletes input value when activated.",
      "tier": "common"
    },
    {
      "name": "size",
      "type": "'small'|'medium'|'large'",
      "default": "medium",
      "description": "Sets the size of the input.",
      "tier": "common"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Sets the value of the input.",
      "tier": "common"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` on the input field to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    },
    {
      "name": "accessible-label-clear-button",
      "type": "string",
      "description": "Sets an aria-label on the clear button to assist screen reader users. Indicates that activating the button will clear the input field.",
      "tier": "advanced"
    },
    {
      "name": "autocomplete",
      "type": "string",
      "description": "Determines whether the browser can provide assistance in filling out the input value and what type of information is expected. This property will override any autocomplete attribute present on the input's parent form element. [Visit MDN for information on supported autocomplete values](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)",
      "tier": "advanced"
    },
    {
      "name": "enterkeyhint",
      "type": "string",
      "description": "Specifies which action label or icon to present for the enter key on virtual keyboards. [Visit MDN for information on supported enterkeyhint values](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint)",
      "tier": "advanced"
    },
    {
      "name": "hide-left-slot",
      "type": "boolean",
      "default": "false",
      "description": "Hides the left slot from input.",
      "tier": "advanced"
    },
    {
      "name": "hide-right-slot",
      "type": "boolean",
      "default": "false",
      "description": "Hides the right slot from input.",
      "tier": "advanced"
    },
    {
      "name": "input-mask",
      "type": "string",
      "description": "Formats user entered data on input based on fixed lengths. This property does not support dynamic formatting or pasted values. See the input mask documentation above for implementation details.",
      "tier": "advanced"
    },
    {
      "name": "inputmode",
      "type": "string",
      "description": "Indicates expected input value type and allows for browsers to display appropriate virtual keyboard. [Visit MDN for information on supported inputmode values](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode)",
      "tier": "advanced"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Sets a name for the input control.",
      "tier": "advanced"
    },
    {
      "name": "show-indicator",
      "type": "boolean",
      "default": "false",
      "description": "Adds a visual indicator next to the label. Indicates that a value is optional(by default) or required if the `required` property is also set.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-select",
      "description": "Dispatched when text is selected. Event payload contains the selected text, the starting index of the selection, and the ending index of the selection. These values can be accessed via `e.detail.selected`, `e.detail.selectionStart`, and `e.detail.selectionEnd`.",
      "payload": "e.detail.selected, e.detail.selectionStart, e.detail.selectionEnd"
    },
    {
      "name": "jh-change",
      "description": "Dispatched when the value of the input has changed and input loses focus. Event payload includes the value of the input and can be accessed via `e.detail.value`. Payload also includes the raw/unformatted value when an input mask is applied and can be accessed via `e.detail.rawValue`.",
      "payload": "e.detail.value, e.detail.rawValue"
    },
    {
      "name": "jh-input",
      "description": "Dispatched when the value of the input has changed. Event payload includes the value of the input and can be accessed via `e.detail.value`. Payload also includes the raw/unformatted value when an input mask is applied and can be accessed via `e.detail.rawValue`.",
      "payload": "e.detail.value, e.detail.rawValue"
    },
    {
      "name": "jh-maxlength",
      "description": "Dispatched when the `maxlength` property is set and it's value is reached."
    },
    {
      "name": "jh-input:clear-button-click",
      "description": "Dispatched when the clear button is activated. Event payload contains the previous value of the input field before it was cleared and can be accessed via `e.detail.previousValue`.",
      "payload": "e.detail.previousValue"
    }
  ],
  "slots": [
    {
      "name": "jh-input-left",
      "description": "Use to insert an element on the left side of the input field, such as an icon or button."
    },
    {
      "name": "jh-input-right",
      "description": "Use to insert an element on the right side of the input field, such as an icon or button."
    },
    {
      "name": "jh-input-clear-button",
      "description": "Use to insert an icon within the clear button."
    }
  ]
}
