// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-list-item>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "disabled",
      "type": "boolean",
      "default": "false",
      "description": "Disables the list-item and prevents all user interactions. May cause list-item to be ignored by assistive technologies(AT).",
      "tier": "common"
    },
    {
      "name": "divider-inset",
      "type": "null|0|8|16|24|32|40|48|56|64|72|80|88|96",
      "description": "The inset of the optional divider. Omit to use the divider-inset token instead.",
      "tier": "common"
    },
    {
      "name": "primary-metadata",
      "type": "string",
      "description": "The text to show as primary metadata.",
      "tier": "common"
    },
    {
      "name": "primary-text",
      "type": "string",
      "description": "The text to show as primary text.",
      "tier": "common"
    },
    {
      "name": "secondary-metadata",
      "type": "string",
      "description": "The text to show as secondary metadata.",
      "tier": "common"
    },
    {
      "name": "secondary-text",
      "type": "string",
      "description": "The text to show as secondary text.",
      "tier": "common"
    },
    {
      "name": "selected",
      "type": "boolean",
      "default": "false",
      "description": "Determines whether an interactive list-item is selected.",
      "tier": "common"
    },
    {
      "name": "show-divider",
      "type": "boolean",
      "default": "false",
      "description": "Determines whether the divider is displayed below the list-item.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert fully customized content into the list-item. Cannot be used with the other slots."
    },
    {
      "name": "jh-list-item-left",
      "description": "Use to insert custom content on the left the list-item."
    },
    {
      "name": "jh-list-item-right",
      "description": "Use to insert custom content on the right the list-item."
    },
    {
      "name": "jh-list-item-content",
      "description": "Use to insert custom content into the list-item."
    },
    {
      "name": "jh-list-item-metadata",
      "description": "Use to insert custom metadata into the list-item."
    }
  ]
}
