// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-list-group>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "label",
      "type": "string",
      "description": "Describes the type of data to be collected.",
      "tier": "common"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert `<jh-list-item>` component(s)."
    }
  ]
}
