// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-notification>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "appearance",
      "type": "'positive'|'neutral'|'negative'",
      "default": "neutral",
      "description": "Sets background color of container to convey message connotation.",
      "tier": "common"
    },
    {
      "name": "hide-dismiss-button",
      "type": "boolean",
      "default": "false",
      "description": "Removes dismiss button from notification.",
      "tier": "common"
    },
    {
      "name": "stacked",
      "type": "boolean",
      "default": "false",
      "description": "Places action button(s) on new line, below default slot.",
      "tier": "common"
    },
    {
      "name": "type",
      "type": "'alert'|'banner'",
      "default": "alert",
      "description": "Determines where in viewport notification is displayed. Alerts will follow typical content flow, while banners will break out of standard flow and go edge-to-edge within a container.",
      "tier": "common"
    },
    {
      "name": "dismiss-button-accessible-label",
      "type": "string",
      "description": "Adds an aria-label to the dismiss button to assist screen readers.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-dismiss",
      "description": "Dispatched when the notification is dismissed."
    }
  ],
  "slots": [
    {
      "name": "",
      "description": "Use to insert contextual information."
    },
    {
      "name": "jh-notification-icon",
      "description": "Use to insert a button or icon to the left of the default slot."
    },
    {
      "name": "jh-notification-dismiss-icon",
      "description": "Use to insert icon within the dismiss button."
    },
    {
      "name": "jh-notification-action",
      "description": "Use to insert action button(s). Placed to the right of the default slot. Set `stacked` property to place slot below default slot."
    }
  ]
}
