// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-progress>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "indeterminate",
      "type": "Boolean",
      "default": "false",
      "description": "Sets the indeterminate state on progress. To be used when progress cannot be calculated.",
      "tier": "common"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Provides information about the item which triggered the progress component.",
      "tier": "common"
    },
    {
      "name": "size",
      "type": "'small'|'medium'|'large'",
      "default": "medium",
      "description": "Sets the size of the progress component.",
      "tier": "common"
    },
    {
      "name": "type",
      "type": "'linear'|'circular'",
      "default": "linear",
      "description": "Determines the style of progress to display.",
      "tier": "common"
    },
    {
      "name": "hide-value",
      "type": "Boolean",
      "default": "false",
      "description": "Hides the `value` text.",
      "tier": "common"
    },
    {
      "name": "max",
      "type": "number",
      "default": "100",
      "description": "Defines the maximum allowed value and sets `aria-valuemax` attribute.",
      "tier": "common"
    },
    {
      "name": "min",
      "type": "number",
      "default": "0",
      "description": "Defines the minimum allowed value and sets `aria-valuemin` attribute.",
      "tier": "common"
    },
    {
      "name": "value",
      "type": "number",
      "default": "0",
      "description": "Specifies how much of the task has been completed. This value is used to calculate the percentage complete based on the min and max values.",
      "tier": "common"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    },
    {
      "name": "accessible-valuetext",
      "type": "string",
      "description": "Sets `aria-valuetext` on progress indicator to provide text alternative of `aria-valuenow`. To be used when progress cannot be represented as a number.",
      "tier": "advanced"
    }
  ],
  "events": [],
  "slots": []
}
