// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-radio-group>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "disabled",
      "type": "boolean",
      "default": "false",
      "description": "Disables the radio group and prevents all user interactions. May cause the group to be ignored by assistive technologies (AT).",
      "tier": "common"
    },
    {
      "name": "error-text",
      "type": "string",
      "description": "Text to be displayed when radio group has failed validation and `invalid` is true.",
      "tier": "common"
    },
    {
      "name": "helper-text",
      "type": "string",
      "description": "Provides additional context or guidance for using the radio group. For `helper-text` to be displayed, the `label` property must also be set.",
      "tier": "common"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "default": "false",
      "description": "Sets an `aria-invalid` on the radio group to indicate the value supplied was invalid and displays `error-text` when set.",
      "tier": "common"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Describes the type of data to be collected.",
      "tier": "common"
    },
    {
      "name": "required",
      "type": "boolean",
      "default": "false",
      "description": "Indicates a value is required.",
      "tier": "common"
    },
    {
      "name": "orientation",
      "type": "'vertical'|'horizontal'",
      "default": "vertical",
      "description": "Determines the orientation of the radio group.",
      "tier": "common"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Sets the value of the radio group.",
      "tier": "common"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Sets the name of the radio group data when submitted in a form.",
      "tier": "advanced"
    },
    {
      "name": "show-indicator",
      "type": "boolean",
      "default": "false",
      "description": "Adds a visual indicator next to the label. Indicates that a value is optional (by default) or required if the `required` property is also set. For the indicator to be displayed, the `label` property must also be set.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-change",
      "description": "Dispatched when the value of the radio group has changed."
    }
  ],
  "slots": [
    {
      "name": "",
      "description": "Use to insert `<jh-radio>` components(s)."
    }
  ]
}
