// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-radio>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "checked",
      "type": "boolean",
      "default": "false",
      "description": "Sets the selected or 'checked' state on the radio.",
      "tier": "common"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "default": "false",
      "description": "Disables the radio and prevents all user interactions. May cause radio to be ignored by assistive technologies(AT).",
      "tier": "common"
    },
    {
      "name": "helper-text",
      "type": "string",
      "description": "Provides additional context or guidance for using the radio. For `helper-text` to be displayed, the `label` property must also be set.",
      "tier": "common"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Sets the value of the data to be collected when selected.",
      "tier": "common"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Sets the value of the radio.",
      "tier": "common"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-change",
      "description": "Dispatched when the state of the radio has changed."
    }
  ],
  "slots": []
}
