// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-switch>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "checked",
      "type": "boolean",
      "default": "false",
      "description": "Sets the selected or 'checked' state on the switch",
      "tier": "common"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "default": "false",
      "description": "Disables the switch and prevents all user interactions. May cause switch to be ignored by assistive technologies(AT). See `accessible-disabled` if switch should remain perceivable to AT.",
      "tier": "common"
    },
    {
      "name": "helper-text",
      "type": "string",
      "description": "Provides additional context or guidance for using the switch. For `helper-text` to be displayed, the `label` property must also be set.",
      "tier": "common"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Describes the intent of the switch.",
      "tier": "common"
    },
    {
      "name": "accessible-disabled",
      "type": "'true'|'false'",
      "description": "Sets an `aria-disabled` to signify to screen readers that the disabled switch should remain perceivable while disabled.",
      "tier": "advanced"
    },
    {
      "name": "accessible-label",
      "type": "string",
      "description": "Sets an `aria-label` to assist screen reader users when no visible label is present.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-change",
      "description": "Dispatched when the state of the switch has changed."
    }
  ],
  "slots": []
}
