// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-table>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "vertical-align",
      "type": "'top' | 'middle' | 'bottom'",
      "default": "top",
      "description": "Sets the vertical alignment for each table cell.",
      "tier": "common"
    },
    {
      "name": "striped",
      "type": "Boolean",
      "default": "false",
      "description": "Applies alternating background colors to rows.",
      "tier": "common"
    },
    {
      "name": "padding",
      "type": "'medium' | 'small'",
      "default": "medium",
      "description": "Adjusts the padding between the rows.",
      "tier": "common"
    },
    {
      "name": "sticky-header",
      "type": "Boolean",
      "default": "false",
      "description": "Allows the header row to remain visible while scrolling.",
      "tier": "common"
    },
    {
      "name": "sticky-footer",
      "type": "Boolean",
      "default": "false",
      "description": "Allows the footer row to remain visible while scrolling.",
      "tier": "common"
    },
    {
      "name": "scrollable",
      "type": "Boolean",
      "default": "false",
      "description": "Makes the table horizontally scrollable on smaller screens.",
      "tier": "common"
    },
    {
      "name": "accessible-label",
      "type": "String",
      "description": "Sets an `aria-label` to assist screen reader users when no visible caption is present.",
      "tier": "advanced"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert table body."
    },
    {
      "name": "jh-table-header",
      "description": "Use to insert table header row."
    },
    {
      "name": "jh-table-footer",
      "description": "Use to insert table footer row."
    },
    {
      "name": "jh-table-caption",
      "description": "Use to insert table caption."
    },
    {
      "name": "jh-table-pagination",
      "description": "Use to insert pagination."
    },
    {
      "name": "jh-table-toolbar",
      "description": "Use to insert toolbar."
    }
  ]
}
