// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-table-row>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert `<jh-table-data-cell>`s or `<jh-table-header-cell>`s."
    }
  ]
}
