// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-tooltip>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "flip-disabled",
      "type": "Boolean",
      "default": "false",
      "description": "Determines whether the tooltip flips to a different position when it reaches the edge of the viewport.",
      "tier": "common"
    },
    {
      "name": "open",
      "type": "Boolean",
      "default": "false",
      "description": "Determines whether the tooltip is open or closed. Can be set on the tooltip to force it open.",
      "tier": "common"
    },
    {
      "name": "position",
      "type": "string",
      "default": "top-center",
      "description": "The position of the tooltip and its arrow.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert the element that triggers the tooltip."
    },
    {
      "name": "jh-tooltip-content",
      "description": "Use to insert the content of the tooltip."
    }
  ]
}
