// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-tag-group>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "alignment",
      "type": "'start'| 'end'",
      "default": "start",
      "description": "Sets the alignment of the tags.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert `<jh-tag>` component(s)."
    }
  ]
}
