// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-toast-controller>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "max-count",
      "type": "number",
      "default": "3",
      "description": "Sets the maximum number of toasts to be displayed at a time.",
      "tier": "common"
    },
    {
      "name": "role",
      "type": "'status'|'alert'",
      "default": "status",
      "description": "Sets the role of the toast controller and establishes a live region to expose changes to assistive technologies.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-dismiss",
      "description": "Dispatched when the toast controller dismisses the oldest toast, and when toasts are dismissed manually by the user."
    }
  ],
  "slots": [
    {
      "name": "",
      "description": "Use to insert `<jh-toast>` components if appending toasts manually."
    }
  ]
}
