// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-table-header-cell>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "horizontal-align",
      "type": "'left' | 'center' | 'right'",
      "default": "left",
      "description": "Sets the horizontal alignment of the content.",
      "tier": "common"
    },
    {
      "name": "sortable",
      "type": "boolean",
      "default": "false",
      "description": "Makes a column sortable.",
      "tier": "common"
    },
    {
      "name": "sorted",
      "type": "'none' | 'ascending' | 'descending'",
      "default": "none",
      "description": "Sets the order in which the items in the column are sorted.",
      "tier": "common"
    }
  ],
  "events": [
    {
      "name": "jh-sort",
      "description": "Dispatched when a sortable header cell is activated. Event payload includes the column, sorted state, and id of the header cell and can be accessed via `e.detail.column`, `e.detail.sorted`, and ` e.detail.id`.",
      "payload": "e.detail.column, e.detail.sorted, e.detail.id"
    }
  ],
  "slots": [
    {
      "name": "jh-table-sorted-ascending",
      "description": "Use to insert a custom icon for ascending sort."
    },
    {
      "name": "jh-table-sorted-descending",
      "description": "Use to insert a custom icon for descending sort."
    },
    {
      "name": "jh-table-sorted-none",
      "description": "Use to insert a custom icon for no sort."
    },
    {
      "name": "",
      "description": "Use to insert table header text."
    }
  ]
}
