// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-tag>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "label",
      "type": "string",
      "description": "Describes the intent of the tag.",
      "tier": "common"
    },
    {
      "name": "dismissible",
      "type": "Boolean",
      "default": "false",
      "description": "Adds a dismiss button to tag. See `remove-on-dismiss` attribute for tag removal.",
      "tier": "common"
    },
    {
      "name": "tooltip-label",
      "type": "string",
      "description": "Adds a tooltip with this string on the dismiss button.",
      "tier": "common"
    },
    {
      "name": "size",
      "type": "'small'| 'medium'",
      "default": "small",
      "description": "Sets the size of the tag.",
      "tier": "common"
    },
    {
      "name": "href",
      "type": "string",
      "description": "Sets the link's destination.",
      "tier": "common"
    },
    {
      "name": "target",
      "type": "string",
      "description": "Specifies where to display the linked URL set by the href property.",
      "tier": "common"
    },
    {
      "name": "remove-on-dismiss",
      "type": "Boolean",
      "default": "false",
      "description": "Removes the tag after the dismiss button is activated.",
      "tier": "common"
    },
    {
      "name": "dismiss-button-accessible-label",
      "type": "string",
      "description": "Adds an aria-label to the dismiss button to assist screen readers.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "jh-dismiss",
      "description": "Dispatched when the tag is dismissed."
    }
  ],
  "slots": [
    {
      "name": "jh-tag-icon",
      "description": "Use to insert an icon to the left of the tag."
    },
    {
      "name": "jh-tag-dismiss-icon",
      "description": "Use to insert a custom icon within the dismiss button."
    }
  ]
}
