// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jh-table-data-cell>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "horizontal-align",
      "type": "'left' | 'center' | 'right'",
      "default": "left",
      "description": "Sets the horizontal alignment of the content.",
      "tier": "common"
    }
  ],
  "events": [],
  "slots": [
    {
      "name": "",
      "description": "Use to insert content."
    }
  ]
}
