// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jha-dialog>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "heading",
      "type": "string",
      "description": "The dialog title, shown centered in the header row.",
      "tier": "common"
    },
    {
      "name": "message-header",
      "type": "string",
      "description": "Optional secondary heading rendered above `message-body` in the default content area (ignored if you use the `dialog-content` slot).",
      "tier": "common"
    },
    {
      "name": "message-body",
      "type": "string",
      "description": "Body text of the default content area (ignored if you use the `dialog-content` slot).",
      "tier": "common"
    },
    {
      "name": "cancel-label",
      "type": "string",
      "description": "Label for the secondary/cancel button. Omitting it (or setting `hide-cancel`) hides the button entirely — there is no default label.",
      "tier": "common"
    },
    {
      "name": "confirm-label",
      "type": "string",
      "default": "'OK'",
      "description": "Label for the primary/confirm button.",
      "tier": "common"
    },
    {
      "name": "confirm-appearance",
      "type": "'danger' | 'success' | ''",
      "default": "''",
      "description": "Styles the confirm button as destructive or affirmative. Leave empty for the default primary appearance.",
      "tier": "common"
    },
    {
      "name": "icon",
      "type": "'warning' | 'success'",
      "description": "Shows a built-in status icon above the message. Omit and use the `icon` slot for a custom one.",
      "tier": "common"
    },
    {
      "name": "hide-header",
      "type": "boolean",
      "default": "false",
      "description": "Hides the entire header row (heading + close button).",
      "tier": "advanced"
    },
    {
      "name": "hide-cancel",
      "type": "boolean",
      "default": "false",
      "description": "Hides the cancel button and the header close (X) button.",
      "tier": "advanced"
    },
    {
      "name": "hide-confirm",
      "type": "boolean",
      "default": "false",
      "description": "Hides the confirm button.",
      "tier": "advanced"
    },
    {
      "name": "async",
      "type": "boolean",
      "default": "false",
      "description": "Set when the `confirm` handler performs an async action and you want the confirm button to hold a pending state until you dismiss the dialog yourself, instead of assuming the click completes immediately.",
      "tier": "advanced"
    },
    {
      "name": "disable-scrolling",
      "type": "boolean",
      "default": "false",
      "description": "Internal — reflects whether background scrolling is currently locked. Not meant to be set directly.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "cancel",
      "description": "Fires when the cancel button or the header close (X) is clicked. Plain event name — not prefixed like `jh-*` events."
    },
    {
      "name": "confirm",
      "description": "Fires when the confirm button is clicked. Plain event name — not prefixed like `jh-*` events."
    }
  ],
  "slots": [
    {
      "name": "icon",
      "description": "Custom icon content, used when the `icon` prop is not set to `warning`/`success`."
    },
    {
      "name": "dialog-content",
      "description": "Replaces the entire default content area (icon + message-header + message-body) with custom markup — e.g. a form."
    },
    {
      "name": "header-left",
      "description": "Content placed before the heading in the header row."
    },
    {
      "name": "header-bottom",
      "description": "Content rendered below the header row, still inside the header region."
    }
  ]
}
