// AUTO-GENERATED by scripts/generate-component-docs.ts — do not edit.
// API surface (props/events/slots) for <jha-advanced-table>, derived from
// @jack-henry/jh-elements' custom-elements.json (hand-authored for legacy
// components with no manifest). Run `npm run generate-docs` after a bump.
import type { ComponentApi } from '../types.js'

export const api: ComponentApi = {
  "props": [
    {
      "name": "columns",
      "type": "TableColumn[]",
      "default": "[]",
      "description": "Column definitions: id (matches a key/path on each row), label, sortBy, searchable, filterType, dataType (e.g. \"badge\", \"currency\", \"date\"), badgeMap, valueFormatter/valueRenderer.",
      "tier": "common"
    },
    {
      "name": "data",
      "type": "DataObject[]",
      "default": "[]",
      "description": "The row data to render. Each object is matched to `columns` by the column `id`.",
      "tier": "common"
    },
    {
      "name": "tableConfig",
      "type": "DataConfiguration | null",
      "default": "null",
      "description": "The single object that drives filters, sort, search query, column order, and groupings — this is the \"config\" prop that customizes most of the table's behavior. Pair with the `table-update` event to make it controlled.",
      "tier": "common"
    },
    {
      "name": "rowActions",
      "type": "RowAction[]",
      "default": "[]",
      "description": "Per-row overflow-menu actions: { id, label, icon?, hiddenCondition?, disabledCondition? }. Selecting one fires `table-row-action`.",
      "tier": "common"
    },
    {
      "name": "bulkActions",
      "type": "boolean",
      "default": "false",
      "description": "Shows a selection checkbox column and the bulk-action toolbar once one or more rows are selected.",
      "tier": "common"
    },
    {
      "name": "selectedItems",
      "type": "string[]",
      "default": "[]",
      "description": "Controlled array of selected row identifiers (matched via `selectedItemIdentifier`). Update it on `bulk-select`.",
      "tier": "common"
    },
    {
      "name": "selectedItemIdentifier",
      "type": "string",
      "default": "'id'",
      "description": "The row field used as each item's unique identifier for selection.",
      "tier": "common"
    },
    {
      "name": "canEditColumns",
      "type": "boolean",
      "default": "false",
      "description": "Shows the column editor (visibility + order) control in the toolbar.",
      "tier": "common"
    },
    {
      "name": "canEditViews",
      "type": "boolean",
      "default": "false",
      "description": "Enables creating/renaming/deleting saved views (paired with the `views` prop).",
      "tier": "common"
    },
    {
      "name": "views",
      "type": "TableView[]",
      "default": "[]",
      "description": "Saved views: named, reusable filter/sort/column configurations the user can switch between.",
      "tier": "common"
    },
    {
      "name": "loading",
      "type": "boolean",
      "default": "false",
      "description": "Shows the loading state in place of rows.",
      "tier": "common"
    },
    {
      "name": "allowRefresh",
      "type": "boolean",
      "default": "false",
      "description": "Shows a refresh button in the toolbar; clicking it fires `refresh-table-data`.",
      "tier": "common"
    },
    {
      "name": "noPagination",
      "type": "boolean",
      "default": "false",
      "description": "Disables pagination and renders every row from `data` at once.",
      "tier": "common"
    },
    {
      "name": "dataPlural",
      "type": "string",
      "default": "'items'",
      "description": "Plural noun used in the row count and default empty-state text, e.g. \"warnings\".",
      "tier": "common"
    },
    {
      "name": "noContentMessage",
      "type": "string",
      "default": "''",
      "description": "Custom empty-state message shown when there are no rows (and no `no-content-message` slot content).",
      "tier": "common"
    },
    {
      "name": "pageLimitOptions",
      "type": "number[]",
      "default": "[10, 25, 50, 100]",
      "description": "Selectable page-size options, shown when `allowPageLimitChange` is true.",
      "tier": "advanced"
    },
    {
      "name": "pageLimit",
      "type": "number",
      "default": "10",
      "description": "Rows per page.",
      "tier": "advanced"
    },
    {
      "name": "pageOffset",
      "type": "number",
      "default": "0",
      "description": "Current pagination offset.",
      "tier": "advanced"
    },
    {
      "name": "allowPageChange",
      "type": "boolean",
      "default": "false",
      "description": "Shows pagination next/back controls.",
      "tier": "advanced"
    },
    {
      "name": "allowPageLimitChange",
      "type": "boolean",
      "default": "false",
      "description": "Shows the page-size selector.",
      "tier": "advanced"
    },
    {
      "name": "apiHasMoreData",
      "type": "boolean",
      "default": "false",
      "description": "For server-paginated data: signals more pages exist beyond what has been loaded.",
      "tier": "advanced"
    },
    {
      "name": "stickyRows",
      "type": "DataObject[]",
      "default": "[]",
      "description": "Rows pinned above the scrollable body (e.g. totals or a highlighted record).",
      "tier": "advanced"
    },
    {
      "name": "stickyHeader",
      "type": "boolean",
      "default": "false",
      "description": "Keeps the column header row fixed while the body scrolls.",
      "tier": "advanced"
    },
    {
      "name": "fullWidthColumns",
      "type": "boolean",
      "default": "false",
      "description": "Stretches columns to fill the available width instead of sizing to content.",
      "tier": "advanced"
    },
    {
      "name": "hideAllView",
      "type": "boolean",
      "default": "false",
      "description": "Hides the built-in \"All\" view tab when `views` are configured.",
      "tier": "advanced"
    },
    {
      "name": "activeViewId",
      "type": "string | null",
      "default": "null",
      "description": "The currently active saved view id.",
      "tier": "advanced"
    },
    {
      "name": "maxVisibleFilters",
      "type": "number",
      "default": "undefined",
      "description": "Caps how many filter controls show before collapsing the rest into an overflow.",
      "tier": "advanced"
    },
    {
      "name": "searchPlaceholderText",
      "type": "string | null",
      "default": "null",
      "description": "Placeholder text for the built-in search input.",
      "tier": "advanced"
    },
    {
      "name": "collapsedGroupIds",
      "type": "string[]",
      "default": "[]",
      "description": "Ids of currently collapsed groups, when row grouping is configured.",
      "tier": "advanced"
    },
    {
      "name": "loadingMore",
      "type": "boolean",
      "default": "false",
      "description": "Shows an inline loading indicator while appending more rows (infinite-scroll style loading).",
      "tier": "advanced"
    },
    {
      "name": "columnWidths",
      "type": "Record<string, number>",
      "default": "{}",
      "description": "Internally-managed measured column widths; rarely set directly.",
      "tier": "advanced"
    },
    {
      "name": "actionPositionValues",
      "type": "RowActionsPositionValues | null",
      "default": "null",
      "description": "Internal layout measurements for positioning the row-actions overflow menu.",
      "tier": "advanced"
    },
    {
      "name": "componentWidth",
      "type": "string | null",
      "default": "null",
      "description": "Internally-measured component width; rarely set directly.",
      "tier": "advanced"
    },
    {
      "name": "tableHeaderWidth",
      "type": "number | null",
      "default": "null",
      "description": "Internally-measured header width; rarely set directly.",
      "tier": "advanced"
    },
    {
      "name": "headerFixed",
      "type": "boolean",
      "default": "false",
      "description": "Internal flag toggled while the sticky header is engaged.",
      "tier": "advanced"
    }
  ],
  "events": [
    {
      "name": "bulk-select",
      "description": "Fires whenever the selection changes (row checkbox, select-all, deselect-all).",
      "payload": "e.detail.items — the full array of currently-selected item ids"
    },
    {
      "name": "table-row-action",
      "description": "Fires when a user chooses an item from a row's overflow-actions menu.",
      "payload": "e.detail.item, e.detail.action"
    },
    {
      "name": "table-cell-click",
      "description": "Fires when a data cell is clicked.",
      "payload": "e.detail.colId, e.detail.item"
    },
    {
      "name": "table-cell-double-click",
      "description": "Fires when a data cell is double-clicked.",
      "payload": "e.detail.colId, e.detail.item"
    },
    {
      "name": "bulk-action",
      "description": "Fires when content slotted into `table-actions` dispatches its own bubbling `bulk-action` event — the table merges in the current selection before re-dispatching.",
      "payload": "e.detail.items, plus whatever detail the slotted trigger dispatched"
    },
    {
      "name": "refresh-table-data",
      "description": "Fires when the refresh button (shown via `allowRefresh`) is clicked."
    },
    {
      "name": "table-update",
      "description": "Fires when the user changes filters, sort, search, column order, or grouping — write `e.detail.config` back into `tableConfig` to keep it controlled.",
      "payload": "e.detail.type ('filters' | 'sort' | 'columnOrder' | 'searchQuery' | 'view-reset' | 'grouping'), e.detail.config"
    },
    {
      "name": "view-change",
      "description": "Fires when the active saved view changes."
    },
    {
      "name": "pagination-backward",
      "description": "Fires when the previous-page control is clicked."
    },
    {
      "name": "pagination-forward",
      "description": "Fires when the next-page control is clicked."
    },
    {
      "name": "page-limit-change",
      "description": "Fires when the page-size selector changes."
    },
    {
      "name": "collapsed-groups-change",
      "description": "Fires when a row group is expanded or collapsed."
    }
  ],
  "slots": [
    {
      "name": "",
      "description": "Content above the search/filter row in the toolbar area — typically a heading."
    },
    {
      "name": "table-actions",
      "description": "The bulk-action toolbar, rendered only while one or more rows are selected. Put buttons/menus here; dispatch a bubbling `bulk-action` event from them to receive the current selection."
    },
    {
      "name": "table-controls",
      "description": "Extra controls appended next to the refresh button and column editor."
    },
    {
      "name": "table-views-right",
      "description": "Extra controls appended next to the saved-views tab bar."
    },
    {
      "name": "header-right",
      "description": "Content pinned to the right end of the column-header row."
    },
    {
      "name": "no-content-message",
      "description": "Overrides the default empty-state message."
    },
    {
      "name": "custom-footer",
      "description": "Content appended at the very bottom, after pagination and sticky rows."
    }
  ]
}
